#!/usr/bin/env bash
# 0. Transfer a file to your server
# "scp" is the command for secure copy.
# "-o "StrictHostKeyChecking=no"" sets an option for the SSH (Secure Shell) connection to the remote host. This option disables the strict host key checking, which means the client will not verify if the host key of the remote server has changed.
# "-i "$4"" specifies the identity file (private key) to be used for public key authentication.
# "$1" represents the path of the file to be transferred from the local host.
# "$3@$2" is the username and the remote host address. "$3" represents the username and "$2" represents the remote host address.
# ":~/" denotes the destination directory on the remote host. In this case, it indicates the user's home directory on the remote system.
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
