#!/usr/bin/env bash
# ufw allow 'Nginx HTTP : This command will permit incoming connections on port 80,
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
