#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.

file="school"
for file in *
do
	if [ -e "$file" ];then
		echo "school file exists"
		if [ -s "$file" ];then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		if [ -f "$file" ];then
			echo "school is a regular file"
		fi
	else
		echo "school file exists"
	fi
done