#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.

file="school"
for file in *
do
	if [ -e "$file" ];then
		echo "school file exists"
	else
		echo "school file exists"
	fi
done